name: Run Python Script

on:
  schedule:
    - cron: '0 12 * * *'  # Spouštění každý den ve 12:00 UTC
  workflow_dispatch:  # Ruční spuštění

jobs:
  run-python-script:  # Toto je název úlohy (job)
    runs-on: ubuntu-latest  # Virtuální prostředí, kde se úloha spustí

    steps:
    - name: Checkout repository  # Nejprve stáhne obsah repozitáře
      uses: actions/checkout@v3

    - name: Set up Python  # Nastaví správnou verzi Pythonu
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Změň podle požadované verze Pythonu

    - name: Install dependencies  # Nainstaluje závislosti
      run: pip install -r requirements.txt

    - name: Run script  # Spustí Python skript
      run: python scraper.py
