name: Run Python Script

on:
  schedule:
    - cron: '0 12 * * *'  # Spouštění každý den ve 12:00 UTC
  workflow_dispatch:  # Ruční spuštění

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository  # Stáhne repozitář
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # Nepoužije automatické přihlašovací údaje

    - name: Set up Python  # Nastaví prostředí Pythonu
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies  # Nainstaluje potřebné knihovny
      run: pip install -r requirements.txt

    - name: Run script  # Spustí tvůj skript
      run: python scraper.py

    - name: Debug Git State After Script  # Debugování po spuštění skriptu
      run: |
        git status  # Zobrazí změny, které vidí Git
        ls -la  # Zobrazí obsah pracovního adresáře
        cat jobs.txt  # Zobrazí obsah jobs.txt pro kontrolu

    - name: Commit and push results
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git stash  # Uloží necommitované změny dočasně mimo pracovní adresář
        git pull origin HEAD:main --rebase  # Synchronizace s repozitářem
        git stash pop  # Vrátí uložené změny zpět do pracovního adresáře
        git add jobs.txt  # Přidá změněný soubor jobs.txt
        git status  # Ověří stav Gitu
        git commit -m "Update scrap results [skip ci]" || echo "No changes to commit"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
